name: doan1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  google_fonts: ^6.2.1
  flip_card: ^0.7.0
  card_swiper: ^3.0.1
  cloud_firestore: ^5.6.0
  percent_indicator: ^4.2.4
  swipable_stack: ^2.0.0
  get: ^4.6.6
  flutter_tts: ^4.2.1
  http: ^1.2.2
  google_sign_in: ^6.2.2
  
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.5
  flutter_ai_toolkit: ^0.6.5
  speech_to_text: ^7.0.0
  string_similarity: ^2.1.1
  googleapis: ^13.2.0
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - lib/images/